backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - label: "Top"
            name: "top"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "Content", name: "content", widget: "string" }
              - { label: "ButtonText", name: "button", widget: "string"}
              - { label: "Image", name: "img", widget: "image"}
          - label: 'Features'
            name: "features"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - label: 'Items'
                name: "items"
                widget: list
                fields:
                  - { label: "Name", name: "name", widget: "string"}
                  - { label: "Description", name: "description", widget: "text"}
                  - { label: "Image", name: "img", widget: "image"}
          - label: "Goal"
            name: "goal"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "string" }
              - { label: "TestContent", name: "test", widget: "string" }
              - { label: "ButtonText", name: "button", widget: "string" }
              - { label: "Image", name: "img", widget: "image" }